apiVersion: v1
kind: ConfigMap
metadata:
  name: ghr-config
  labels:
    {{- include "ghr.labels" . | nindent 4 }}
data:
  ORG: {{ .Values.ghr.ORG }}
  NAME: {{ .Values.ghr.NAME }}
  TOKEN: {{ .Values.ghr.TOKEN }}
